on: [push]

jobs:
  e2e:
    runs-on: ubuntu-latest
    name: Test rendering .drawio files
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # Needed for resolving version information
          fetch-depth: 0
      - name: Render .drawio files
        uses: ./
        with:
          formats: "png,pdf,jpg,svg"
          log-level: "debug"
        id: render
      - name: Print the rendered files
        run: echo "The files that changed were ${{ steps.render.outputs.rendered-files }}"
      - name: Verify test files are present
        run: 'make verify'
